spring:
  datasource:
    url: jdbc:h2:file:./casino
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

telegram:
  bot:
    username: "testingWHA_bot"
    token: "7658455128:AAFo78WyqQnw0HQjp3nDbSLtIToty1Lxh8M"
    webapp-url: "https://mini-app-v555.onrender.com"

server:
  port: 8080
  servlet:
    context-path: / 